/**
 * DO NOT EDIT DIRECTLY — generated by Style Dictionary.
 * Values:   tokens/*.json
 * Contract: style-dictionary.config.mjs
 * Rebuild:  npm run tokens
 */

export type ThemeMode = "dark" | "light";

/** Semantic color tokens, resolved per theme. Keys map 1:1 to `--` CSS vars. */
export const themeTokens = {
  dark: {
    "bg-primary": "#0f1117",
    "bg-primary-rgb": "15, 17, 23",
    "bg-secondary": "#1a1d27",
    "bg-tertiary": "#242736",
    "bg-hover": "#2a2e3d",
    "bg-elevated": "#20232f",
    "surface-overlay-rgb": "26, 29, 39",
    "text-primary": "#e8eaed",
    "text-secondary": "#b0b6bd",
    "text-muted": "#9099a6",
    "text-inverse": "#ffffff",
    border: "#2e3140",
    "border-strong": "#3a3e50",
    accent: "#6355e8",
    "accent-rgb": "99, 85, 232",
    "accent-hover": "#5749d4",
    success: "#5fd68a",
    error: "#f28b82",
    warning: "#fbbc04",
    running: "#6ea8fe",
    "success-rgb": "61, 220, 151",
    "error-rgb": "234, 67, 53",
    "warning-rgb": "251, 188, 5",
    "running-rgb": "110, 168, 254",
    "success-text": "#c8f7d8",
    "error-text": "#ffd5d1",
    "warning-text": "#ffe8a3",
    "running-text": "#c5dcff",
    "elevate-rgb": "255, 255, 255",
    "scrim-rgb": "0, 0, 0",
    shadow: "0 2px 8px rgba(0, 0, 0, 0.3)",
  },
  light: {
    "bg-primary": "#f5f6f8",
    "bg-primary-rgb": "245, 246, 248",
    "bg-secondary": "#ffffff",
    "bg-tertiary": "#eef0f4",
    "bg-hover": "#e6e9ef",
    "bg-elevated": "#ffffff",
    "surface-overlay-rgb": "255, 255, 255",
    "text-primary": "#1a1d27",
    "text-secondary": "#4c5563",
    "text-muted": "#57606f",
    "text-inverse": "#ffffff",
    border: "#d9dde5",
    "border-strong": "#c3c9d4",
    accent: "#5646d6",
    "accent-rgb": "86, 70, 214",
    "accent-hover": "#4436c0",
    success: "#1f9d57",
    error: "#c62828",
    warning: "#b7791f",
    running: "#2f6fed",
    "success-rgb": "31, 157, 87",
    "error-rgb": "214, 69, 69",
    "warning-rgb": "183, 121, 31",
    "running-rgb": "47, 111, 237",
    "success-text": "#1f7a46",
    "error-text": "#a93232",
    "warning-text": "#8a5a12",
    "running-text": "#23508f",
    "elevate-rgb": "15, 17, 23",
    "scrim-rgb": "15, 23, 42",
    shadow: "0 2px 8px rgba(15, 23, 42, 0.12)",
  },
} as const;

/** Mode-agnostic tokens (radius, type scale, spacing, motion, fonts). */
export const baseTokens = {
  radius: "8px",
  "radius-lg": "12px",
  "font-size-xs": "11px",
  "font-size-sm": "12px",
  "font-size-md": "13px",
  "font-size-lg": "15px",
  "font-size-xl": "18px",
  "font-size-2xl": "22px",
  "line-height-tight": "1.25",
  "line-height-normal": "1.5",
  "font-mono": '"SF Mono", "Menlo", "Monaco", monospace',
  "font-sans":
    '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  "space-1": "4px",
  "space-2": "8px",
  "space-3": "12px",
  "space-4": "16px",
  "space-5": "20px",
  "space-6": "24px",
  "space-8": "32px",
  "duration-fast": "0.15s",
  "duration-base": "0.2s",
  "duration-slow": "0.3s",
  "ease-standard": "cubic-bezier(0.4, 0, 0.2, 1)",
  "ease-out": "cubic-bezier(0, 0, 0.2, 1)",
  "ease-in": "cubic-bezier(0.4, 0, 1, 1)",
} as const;

export type ThemeTokenName = keyof (typeof themeTokens)["dark"];
export type BaseTokenName = keyof typeof baseTokens;
export type TokenName = ThemeTokenName | BaseTokenName;
